# 指定版本
version: '3.8'
services:
  miaoyou_server: 
      build: 
        context: ./miaoyou_server
      # network_mode: "host"      
      ports: 
        - 8200:8200     
  # nginx的配置
  nginx:
      # 重启
      restart: always
      image: nginx
      build: 
        context: . 
      # 配置映射
      ports: 
        - 80:80  
      volumes: 
        - ./config/api.bairdweng.com.conf:/etc/nginx/conf.d/api.bairdweng.com.conf
